spring:
  application:
    name: ldsg-pages
  resources:
    static-locations: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 100
  thymeleaf:
    cache: false
#开发时关闭缓存,不然没法看到实时页面
server:
  port: 5521

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance: #服务名称的修改
    instance-id: ldsg-pages
    prefer-ip-address: true     #访问路径可以显示IP地址
