server:
  port: 3333
spring:
  application:
    name: ldsg-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/

  instance: #服务名称的修改
    instance-id: ldsg-gateway-zuul
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: ldsg-gateway
  company.name: www.ldsg.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  build.description: ${project.description}
#zuul网关的配置
zuul:
  prefix: /api # 设置统一的公共前缀
  ignored-services: "* "#原真实服务名忽略，忽略全部用“*”,忽略一个用服务名
  routes:
    server-goods: #面向服务的路由配置，可以自定义设置名称
      serviceId: ldsg-goods #服务名
      path: /goods/** #映射的url
    server-landing: #面向服务的路由配置，可以自定义设置名称
      serviceId: ldsg-landing #服务名
      path: /landing/** #映射的url
    server-session: #面向服务的路由配置，可以自定义设置名称
      serviceId: ldsg-sso #服务名
      path: /sso/** #映射的url
